[project]
name = "budget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "openai>=1.91.0",
    "pandas>=2.3.0",
    "werkzeug>=3.1.3",
]
